Traceback (most recent call last):
  File "H:\pychram\pulled\newtest\newscriptmulti.py", line 366, in <module>
    all_resources.extend(collect_resources_for_region(region))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\pychram\pulled\newtest\newscriptmulti.py", line 204, in collect_resources_for_region
    tags = get_resource_tags(dynamodb_client, table_arn, 'dynamodb')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\pychram\pulled\newtest\newscriptmulti.py", line 74, in get_resource_tags
    response = client.list_tags_for_resource(resourceArn=resource_arn)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\F37YHCS\AppData\Roaming\Python\Python311\site-packages\botocore\client.py", line 918, in __getattr__
    raise AttributeError(
AttributeError: 'DynamoDB' object has no attribute 'list_tags_for_resource'. Did you mean: 'list_tags_of_resource'?
